### ISSUE TITLE
Test that charms without the service mesh relation still work in a service-mesh-enabled model

### ISSUE THREAD

**Issue by ca-scribner** [canonical/istio-k8s-operator#14]
### Enhancement Proposal

We should test that charms that do not use the service mesh library (and thus are not explicitly added to a service mesh) still function properly:
1. when the model **is not** subscribed to the mesh
  a. with hardened mode **disabled**
  b. with hardened mode **enabled**
2. when the model **is** subscribed to the mesh
  a. with hardened mode **disabled**
  b. with hardened mode **enabled**  <-- charm should function, but might not be reachable by other charms

**Comment by IbraAoad** [comment]
## Test 1: COS Lite + Flogs + Beacon

Configuration: model-on-mesh set to true.
### Observed Issue 1 (bind: address already in use):
When connection is reset to the juju controller, charms goes into error state with msg (bind: address already in use), Sometimes, the issue resolves on its own; sometimes it doesn't.

Error Logs:
```
unit-traefik-0: 17:40:52 ERROR unit.traefik/0.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "./src/charm.py", line 1212, in <module>
    main(TraefikIngressCharm, use_juju_for_storage=True)
  File "/var/lib/juju/agents/unit-traefik-0/charm/venv/ops/main.py", line 551, in main
    manager.run()
  File "/var/lib/juju/agents/unit-traefik-0/charm/venv/ops/main.py", line 530, in run
    self._emit()
  File "/var/lib/juju/agents/unit-traefik-0/charm/venv/ops/main.py", line 519, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name)
  File "/var/lib/juju/agents/unit-traefik-0/charm/venv/ops/main.py", line 147, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-traefik-0/charm/venv/ops/framework.py", line 348, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-traefik-0/charm/venv/ops/framework.py", line 860, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-traefik-0/charm/venv/ops/framework.py", line 950, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-traefik-0/charm/lib/charms/tempo_k8s/v1/charm_tracing.py", line 735, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "./src/charm.py", line 508, in _on_traefik_pebble_ready
    self._clear_all_configs_and_restart_traefik()
  File "/var/lib/juju/agents/unit-traefik-0/charm/lib/charms/tempo_k8s/v1/charm_tracing.py", line 735, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "./src/charm.py", line 524, in _clear_all_configs_and_restart_traefik
    self._restart_traefik()
  File "/var/lib/juju/agents/unit-traefik-0/charm/lib/charms/tempo_k8s/v1/charm_tracing.py", line 735, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "./src/charm.py", line 1079, in _restart_traefik
    self.traefik.restart()
  File "/var/lib/juju/agents/unit-traefik-0/charm/src/traefik.py", line 636, in restart
    self._container.restart(self.service_name)
  File "/var/lib/juju/agents/unit-traefik-0/charm/venv/ops/model.py", line 2274, in restart
    self._pebble.restart_services(service_names)
  File "/var/lib/juju/agents/unit-traefik-0/charm/venv/ops/pebble.py", line 2201, in restart_services
    return self._services_action('restart', services, timeout, delay)
  File "/var/lib/juju/agents/unit-traefik-0/charm/venv/ops/pebble.py", line 2226, in _services_action
    raise ChangeError(change.err, change)
ops.pebble.ChangeError: cannot perform the following tasks:
2024/09/02 17:40:52 traefik.go:80: command /bin/traefik error: error while building entryPoint web: error preparing server: error opening listener: listen tcp :80: bind: address already in use
2024-09-02T17:40:52Z ERROR cannot start service: exited quickly with code 1
- Start service "traefik" (cannot start service: exited quickly with code 1)
unit-traefik-0: 17:40:56 INFO unit.traefik/0.juju-log Kubernetes service 'traefik' patched successfully
```
```
2024-09-02T19:26:04.491Z [grafana] logger=server t=2024-09-02T19:26:04.491882937Z level=error msg="Stopped background service" service=*api.HTTPServer reason="failed to open listener on address 0.0.0.0:3000: listen tcp 0.0.0.0:3000: bind: address already in use"
2024-09-02T19:26:04.493Z [grafana] logger=infra.usagestats.collector t=2024-09-02T19:26:04.493313017Z level=error msg="Failed to get datasource stats" error="context canceled"
2024-09-02T19:26:04.495Z [grafana] logger=auth t=2024-09-02T19:26:04.49519678Z level=error msg="failed to lock and execute cleanup of expired auth token" error="context canceled"
2024-09-02T19:26:04.499Z [grafana] Error: ✗ *api.HTTPServer run error: failed to open listener on address 0.0.0.0:3000: listen tcp 0.0.0.0:3000: bind: address already in use
2024-09-02T19:26:04.513Z [pebble] Service "grafana" stopped unexpectedly with code 1
```
### Observed Issue 2:
Charms aren't able to connect to other charms ingress URL
Error Logs (Ztunnel & Grafana when trying to test alertmanager source connection via the alertmanager ingress URL):
```
2024-09-02T18:59:08.773803Z     info    access  connection complete     src.addr=10.1.20.7:49858 src.workload=grafana-k8s-0 src.namespace=k8s src.identity="spiffe://cluster.local/ns/k8s/sa/grafana-k8s" dst.addr=10.1.20.42:15008 dst.hbone_addr=172.232.192.178:80 dst.service=istio-ingress-k8s-istio.k8s.svc.cluster.local dst.workload=istio-beacon-k8s-k8s-waypoint-cc46d4bd4-j7592 dst.namespace=k8s dst.identity="spiffe://cluster.local/ns/k8s/sa/istio-beacon-k8s-k8s-waypoint" direction="outbound" bytes_sent=636 bytes_recv=0 duration="1ms"
2024-09-02T18:59:08.917470Z     info    access  connection complete     src.addr=10.1.20.7:49870 src.workload=grafana-k8s-0 src.namespace=k8s src.identity="spiffe://cluster.local/ns/k8s/sa/grafana-k8s" dst.addr=10.1.20.42:15008 dst.hbone_addr=172.232.192.178:80 dst.service=istio-ingress-k8s-istio.k8s.svc.cluster.local dst.workload=istio-beacon-k8s-k8s-waypoint-cc46d4bd4-j7592 dst.namespace=k8s dst.identity="spiffe://cluster.local/ns/k8s/sa/istio-beacon-k8s-k8s-waypoint" direction="outbound" bytes_sent=639 bytes_recv=0 duration="1ms"
2024-09-02T18:59:09.045119Z     info    access  connection complete     src.addr=10.1.20.7:49872 src.workload=grafana-k8s-0 src.namespace=k8s src.identity="spiffe://cluster.local/ns/k8s/sa/grafana-k8s" dst.addr=10.1.20.42:15008 dst.hbone_addr=172.232.192.178:80 dst.service=istio-ingress-k8s-istio.k8s.svc.cluster.local dst.workload=istio-beacon-k8s-k8s-waypoint-cc46d4bd4-j7592 dst.namespace=k8s dst.identity="spiffe://cluster.local/ns/k8s/sa/istio-beacon-k8s-k8s-waypoint" direction="outbound" bytes_sent=626 bytes_recv=0 duration="1ms"
```
```
2024-09-02T18:59:08.773Z [grafana] logger=data-proxy-log userId=1 orgId=1 uname=admin path=/api/datasources/proxy/uid/P6B7DA9DF455CD317/api/v1/status/buildinfo remote_addr=172.232.192.178 referer=http://localhost:3000/connections/your-connections/datasources/edit/P6B7DA9DF455CD317 t=2024-09-02T18:59:08.773799017Z level=error msg="Proxy request failed" err=EOF
2024-09-02T18:59:08.773Z [grafana] logger=context userId=1 orgId=1 uname=admin t=2024-09-02T18:59:08.773918688Z level=error msg="Request Completed" method=GET path=/api/datasources/proxy/uid/P6B7DA9DF455CD317/api/v1/status/buildinfo status=502 remote_addr=172.232.192.178 time_ms=3 duration=3.273419ms size=0 referer=http://localhost:3000/connections/your-connections/datasources/edit/P6B7DA9DF455CD317 handler=/api/datasources/proxy/uid/:uid/*
2024-09-02T18:59:08.917Z [grafana] logger=data-proxy-log userId=1 orgId=1 uname=admin path=/api/datasources/proxy/uid/P6B7DA9DF455CD317/alertmanager/api/v2/status remote_addr=172.232.192.178 referer=http://localhost:3000/connections/your-connections/datasources/edit/P6B7DA9DF455CD317 t=2024-09-02T18:59:08.917492951Z level=error msg="Proxy request failed" err=EOF
2024-09-02T18:59:08.917Z [grafana] logger=context userId=1 orgId=1 uname=admin t=2024-09-02T18:59:08.917601632Z level=error msg="Request Completed" method=GET path=/api/datasources/proxy/uid/P6B7DA9DF455CD317/alertmanager/api/v2/status status=502 remote_addr=172.232.192.178 time_ms=2 duration=2.948266ms size=0 referer=http://localhost:3000/connections/your-connections/datasources/edit/P6B7DA9DF455CD317 handler=/api/datasources/proxy/uid/:uid/*
2024-09-02T18:59:09.045Z [grafana] logger=data-proxy-log userId=1 orgId=1 uname=admin path=/api/datasources/proxy/uid/P6B7DA9DF455CD317/api/v2/status remote_addr=172.232.192.178 referer=http://localhost:3000/connections/your-connections/datasources/edit/P6B7DA9DF455CD317 t=2024-09-02T18:59:09.045112514Z level=error msg="Proxy request failed" err=EOF
2024-09-02T18:59:09.045Z [grafana] logger=context userId=1 orgId=1 uname=admin t=2024-09-02T18:59:09.045213895Z level=error msg="Request Completed" method=GET path=/api/datasources/proxy/uid/P6B7DA9DF455CD317/api/v2/status status=502 remote_addr=172.232.192.178 time_ms=2 duration=2.562673ms size=0 referer=http://localhost:3000/connections/your-connections/datasources/edit/P6B7DA9DF455CD317 handler=/api/datasources/proxy/uid/:uid/*
2024-09-02T18:59:26.507Z [pebble] GET /v1/notices?after=2024-09-02T18%3A45%3A56.448244008Z&timeout=30s 30.000408363s 200
```
## Test 2: Istio Ingress k8s + Beacon + Grafana + Alertmanager
Configuration: model-on-mesh set to true.
### Observed Issues
Same observed issues as Test 1
- Pods are no longer able to ping external URL of other pods

## Test 3: Istio Ingress k8s + Beacon* + Grafana + Alertmanager
Configuration: 
- model-on-mesh set to true.
- Updated Beacon's waypoint configs to be
  - {"istio.io/waypoint-for": "all"} instead of {"istio.io/waypoint-for": "service"}
  - {"from": "Same"} instead of {"from": "All"}
### Observed Issues
Same observed issues as Test 1&2
- Pods are no longer able to ping external URL of other pods


## Test 4: ( COS Lite + Flogs + manually adding ambient label with no waypoint )
Configuration: model-on-mesh set to true.
### Result: 
bind error for traefik still appeared yet resolved on it's own after a short while, afterwards **all functionality for COS-lite worked fine and traffic is going correctly through the mesh**

![image](https://github.com/user-attachments/assets/9fd0f6d0-f0ce-4437-9efb-57298e8153b8)

**Comment by IbraAoad** [comment]
Closing this issue as work will continue on https://github.com/canonical/istio-beacon-k8s-operator/issues/11 and https://github.com/canonical/istio-beacon-k8s-operator/issues/10
